/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoadoutsRouteImport } from './routes/loadouts'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlaybookIndexRouteImport } from './routes/playbook/index'
import { Route as PlaybookSlugRouteImport } from './routes/playbook/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadoutsRoute = LoadoutsRouteImport.update({
  id: '/loadouts',
  path: '/loadouts',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookIndexRoute = PlaybookIndexRouteImport.update({
  id: '/playbook/',
  path: '/playbook/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookSlugRoute = PlaybookSlugRouteImport.update({
  id: '/playbook/$slug',
  path: '/playbook/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loadouts': typeof LoadoutsRoute
  '/maps': typeof MapsRoute
  '/roles': typeof RolesRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/playbook/': typeof PlaybookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loadouts': typeof LoadoutsRoute
  '/maps': typeof MapsRoute
  '/roles': typeof RolesRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/playbook': typeof PlaybookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loadouts': typeof LoadoutsRoute
  '/maps': typeof MapsRoute
  '/roles': typeof RolesRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/playbook/$slug': typeof PlaybookSlugRoute
  '/playbook/': typeof PlaybookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/loadouts'
    | '/maps'
    | '/roles'
    | '/saved'
    | '/settings'
    | '/playbook/$slug'
    | '/playbook/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/loadouts'
    | '/maps'
    | '/roles'
    | '/saved'
    | '/settings'
    | '/playbook/$slug'
    | '/playbook'
  id:
    | '__root__'
    | '/'
    | '/loadouts'
    | '/maps'
    | '/roles'
    | '/saved'
    | '/settings'
    | '/playbook/$slug'
    | '/playbook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoadoutsRoute: typeof LoadoutsRoute
  MapsRoute: typeof MapsRoute
  RolesRoute: typeof RolesRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  PlaybookSlugRoute: typeof PlaybookSlugRoute
  PlaybookIndexRoute: typeof PlaybookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loadouts': {
      id: '/loadouts'
      path: '/loadouts'
      fullPath: '/loadouts'
      preLoaderRoute: typeof LoadoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/': {
      id: '/playbook/'
      path: '/playbook'
      fullPath: '/playbook/'
      preLoaderRoute: typeof PlaybookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/$slug': {
      id: '/playbook/$slug'
      path: '/playbook/$slug'
      fullPath: '/playbook/$slug'
      preLoaderRoute: typeof PlaybookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoadoutsRoute: LoadoutsRoute,
  MapsRoute: MapsRoute,
  RolesRoute: RolesRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  PlaybookSlugRoute: PlaybookSlugRoute,
  PlaybookIndexRoute: PlaybookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
